<!DOCTYPE html "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
      <title>Zendcasts</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

  </head>
    <body >
    <h1>Writing Action Stack Plugins</h1>
    <h2><?= $this->message; ?></h2>
    <form method="post">
	<input type="text" id="secret" name="secret" />
	<input type="submit" />
    </form>
	<a href="/assets/image.jpg">grab special asset</a>
    </body>
</html>