<!DOCTYPE html "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>Zendcasts</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <style>
	body
	{
	    background: #333;
	}
	h1
	{
	    color: #FF0000;
	}
	#container
	{
	    margin: 0 auto;
	    width: 500px;
	    background: #FFF;
	}
    </style>
  </head>
  <body>
      <div id="container">

	<?= $this->layout()->content; ?>
      </div>
  </body>
</html>