/*
Navicat MySQL Data Transfer
Source Host     : localhost:3306
Source Database : firebug
Target Host     : localhost:3306
Target Database : firebug
Date: 7/18/2009 3:24:53 PM
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for countries
-- ----------------------------
DROP TABLE IF EXISTS `countries`;
CREATE TABLE `countries` (
  `countryid` int(11) NOT NULL auto_increment,
  `countrycouregid` int(11) default NULL,
  `countryname` varchar(255) NOT NULL default '',
  `countryiso2` char(2) NOT NULL default '',
  `countryiso3` char(3) NOT NULL default '',
  PRIMARY KEY  (`countryid`),
  KEY `i_regions_countrycouregid` (`countrycouregid`)
) ENGINE=MyISAM AUTO_INCREMENT=240 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of countries
-- ----------------------------
INSERT INTO `countries` VALUES ('1', null, 'Afghanistan', 'AF', 'AFG');
INSERT INTO `countries` VALUES ('2', null, 'Albania', 'AL', 'ALB');
INSERT INTO `countries` VALUES ('3', null, 'Algeria', 'DZ', 'DZA');
INSERT INTO `countries` VALUES ('4', null, 'American Samoa', 'AS', 'ASM');
INSERT INTO `countries` VALUES ('5', null, 'Andorra', 'AD', 'AND');
INSERT INTO `countries` VALUES ('6', null, 'Angola', 'AO', 'AGO');
INSERT INTO `countries` VALUES ('7', null, 'Anguilla', 'AI', 'AIA');
INSERT INTO `countries` VALUES ('8', null, 'Antarctica', 'AQ', '\r');
INSERT INTO `countries` VALUES ('9', null, 'Antigua and Barbuda', 'AG', 'ATG');
INSERT INTO `countries` VALUES ('10', null, 'Argentina', 'AR', 'ARG');
INSERT INTO `countries` VALUES ('11', null, 'Armenia', 'AM', 'ARM');
INSERT INTO `countries` VALUES ('12', null, 'Aruba', 'AW', 'ABW');
INSERT INTO `countries` VALUES ('13', null, 'Australia', 'AU', 'AUS');
INSERT INTO `countries` VALUES ('14', '1', 'Austria', 'AT', 'AUT');
INSERT INTO `countries` VALUES ('15', null, 'Azerbaijan', 'AZ', 'AZE');
INSERT INTO `countries` VALUES ('16', null, 'Bahamas', 'BS', 'BHS');
INSERT INTO `countries` VALUES ('17', null, 'Bahrain', 'BH', 'BHR');
INSERT INTO `countries` VALUES ('18', null, 'Bangladesh', 'BD', 'BGD');
INSERT INTO `countries` VALUES ('19', null, 'Barbados', 'BB', 'BRB');
INSERT INTO `countries` VALUES ('20', null, 'Belarus', 'BY', 'BLR');
INSERT INTO `countries` VALUES ('21', '1', 'Belgium', 'BE', 'BEL');
INSERT INTO `countries` VALUES ('22', null, 'Belize', 'BZ', 'BLZ');
INSERT INTO `countries` VALUES ('23', null, 'Benin', 'BJ', 'BEN');
INSERT INTO `countries` VALUES ('24', null, 'Bermuda', 'BM', 'BMU');
INSERT INTO `countries` VALUES ('25', null, 'Bhutan', 'BT', 'BTN');
INSERT INTO `countries` VALUES ('26', null, 'Bolivia', 'BO', 'BOL');
INSERT INTO `countries` VALUES ('27', null, 'Bosnia and Herzegovina', 'BA', 'BIH');
INSERT INTO `countries` VALUES ('28', null, 'Botswana', 'BW', 'BWA');
INSERT INTO `countries` VALUES ('29', null, 'Bouvet Island', 'BV', 'NUL');
INSERT INTO `countries` VALUES ('30', null, 'Brazil', 'BR', 'BRA');
INSERT INTO `countries` VALUES ('31', null, 'British Indian Ocean Territory', 'IO', 'NUL');
INSERT INTO `countries` VALUES ('32', null, 'Brunei Darussalam', 'BN', 'BRN');
INSERT INTO `countries` VALUES ('33', '1', 'Bulgaria', 'BG', 'BGR');
INSERT INTO `countries` VALUES ('34', null, 'Burkina Faso', 'BF', 'BFA');
INSERT INTO `countries` VALUES ('35', null, 'Burundi', 'BI', 'BDI');
INSERT INTO `countries` VALUES ('36', null, 'Cambodia', 'KH', 'KHM');
INSERT INTO `countries` VALUES ('37', null, 'Cameroon', 'CM', 'CMR');
INSERT INTO `countries` VALUES ('38', null, 'Canada', 'CA', 'CAN');
INSERT INTO `countries` VALUES ('39', null, 'Cape Verde', 'CV', 'CPV');
INSERT INTO `countries` VALUES ('40', null, 'Cayman Islands', 'KY', 'CYM');
INSERT INTO `countries` VALUES ('41', null, 'Central African Republic', 'CF', 'CAF');
INSERT INTO `countries` VALUES ('42', null, 'Chad', 'TD', 'TCD');
INSERT INTO `countries` VALUES ('43', null, 'Chile', 'CL', 'CHL');
INSERT INTO `countries` VALUES ('44', null, 'China', 'CN', 'CHN');
INSERT INTO `countries` VALUES ('45', null, 'Christmas Island', 'CX', 'NUL');
INSERT INTO `countries` VALUES ('46', null, 'Cocos (Keeling) Islands', 'CC', 'NUL');
INSERT INTO `countries` VALUES ('47', null, 'Colombia', 'CO', 'COL');
INSERT INTO `countries` VALUES ('48', null, 'Comoros', 'KM', 'COM');
INSERT INTO `countries` VALUES ('49', null, 'Congo', 'CG', 'COG');
INSERT INTO `countries` VALUES ('50', null, 'Congo, the Democratic Republic of the', 'CD', 'COD');
INSERT INTO `countries` VALUES ('51', null, 'Cook Islands', 'CK', 'COK');
INSERT INTO `countries` VALUES ('52', null, 'Costa Rica', 'CR', 'CRI');
INSERT INTO `countries` VALUES ('54', null, 'Croatia', 'HR', 'HRV');
INSERT INTO `countries` VALUES ('55', null, 'Cuba', 'CU', 'CUB');
INSERT INTO `countries` VALUES ('56', null, 'Cyprus', 'CY', 'CYP');
INSERT INTO `countries` VALUES ('57', null, 'Czech Republic', 'CZ', 'CZE');
INSERT INTO `countries` VALUES ('58', null, 'Denmark', 'DK', 'DNK');
INSERT INTO `countries` VALUES ('59', null, 'Djibouti', 'DJ', 'DJI');
INSERT INTO `countries` VALUES ('60', null, 'Dominica', 'DM', 'DMA');
INSERT INTO `countries` VALUES ('61', null, 'Dominican Republic', 'DO', 'DOM');
INSERT INTO `countries` VALUES ('62', null, 'Ecuador', 'EC', 'ECU');
INSERT INTO `countries` VALUES ('63', null, 'Egypt', 'EG', 'EGY');
INSERT INTO `countries` VALUES ('64', null, 'El Salvador', 'SV', 'SLV');
INSERT INTO `countries` VALUES ('65', null, 'Equatorial Guinea', 'GQ', 'GNQ');
INSERT INTO `countries` VALUES ('66', null, 'Eritrea', 'ER', 'ERI');
INSERT INTO `countries` VALUES ('67', null, 'Estonia', 'EE', 'EST');
INSERT INTO `countries` VALUES ('68', null, 'Ethiopia', 'ET', 'ETH');
INSERT INTO `countries` VALUES ('69', null, 'Falkland Islands (Malvinas)', 'FK', 'FLK');
INSERT INTO `countries` VALUES ('70', null, 'Faroe Islands', 'FO', 'FRO');
INSERT INTO `countries` VALUES ('71', null, 'Fiji', 'FJ', 'FJI');
INSERT INTO `countries` VALUES ('72', '1', 'Finland', 'FI', 'FIN');
INSERT INTO `countries` VALUES ('73', '1', 'France', 'FR', 'FRA');
INSERT INTO `countries` VALUES ('74', null, 'French Guiana', 'GF', 'GUF');
INSERT INTO `countries` VALUES ('75', null, 'French Polynesia', 'PF', 'PYF');
INSERT INTO `countries` VALUES ('76', null, 'French Southern Territories', 'TF', 'NUL');
INSERT INTO `countries` VALUES ('77', null, 'Gabon', 'GA', 'GAB');
INSERT INTO `countries` VALUES ('78', null, 'Gambia', 'GM', 'GMB');
INSERT INTO `countries` VALUES ('79', null, 'Georgia', 'GE', 'GEO');
INSERT INTO `countries` VALUES ('80', '1', 'Germany', 'DE', 'DEU');
INSERT INTO `countries` VALUES ('81', null, 'Ghana', 'GH', 'GHA');
INSERT INTO `countries` VALUES ('82', null, 'Gibraltar', 'GI', 'GIB');
INSERT INTO `countries` VALUES ('83', '1', 'Greece', 'GR', 'GRC');
INSERT INTO `countries` VALUES ('84', null, 'Greenland', 'GL', 'GRL');
INSERT INTO `countries` VALUES ('85', null, 'Grenada', 'GD', 'GRD');
INSERT INTO `countries` VALUES ('86', null, 'Guadeloupe', 'GP', 'GLP');
INSERT INTO `countries` VALUES ('87', null, 'Guam', 'GU', 'GUM');
INSERT INTO `countries` VALUES ('88', null, 'Guatemala', 'GT', 'GTM');
INSERT INTO `countries` VALUES ('89', null, 'Guinea', 'GN', 'GIN');
INSERT INTO `countries` VALUES ('90', null, 'Guinea-Bissau', 'GW', 'GNB');
INSERT INTO `countries` VALUES ('91', null, 'Guyana', 'GY', 'GUY');
INSERT INTO `countries` VALUES ('92', null, 'Haiti', 'HT', 'HTI');
INSERT INTO `countries` VALUES ('93', null, 'Heard Island and Mcdonald Islands', 'HM', '\r');
INSERT INTO `countries` VALUES ('94', null, 'Holy See (Vatican City State)', 'VA', 'VAT');
INSERT INTO `countries` VALUES ('95', null, 'Honduras', 'HN', 'HND');
INSERT INTO `countries` VALUES ('96', null, 'Hong Kong', 'HK', 'HKG');
INSERT INTO `countries` VALUES ('97', null, 'Hungary', 'HU', 'HUN');
INSERT INTO `countries` VALUES ('98', null, 'Iceland', 'IS', 'ISL');
INSERT INTO `countries` VALUES ('99', null, 'India', 'IN', 'IND');
INSERT INTO `countries` VALUES ('100', null, 'Indonesia', 'ID', 'IDN');
INSERT INTO `countries` VALUES ('101', null, 'Iran, Islamic Republic of', 'IR', 'IRN');
INSERT INTO `countries` VALUES ('102', null, 'Iraq', 'IQ', 'IRQ');
INSERT INTO `countries` VALUES ('103', '1', 'Ireland', 'IE', 'IRL');
INSERT INTO `countries` VALUES ('104', null, 'Israel', 'IL', 'ISR');
INSERT INTO `countries` VALUES ('105', '1', 'Italy', 'IT', 'ITA');
INSERT INTO `countries` VALUES ('106', null, 'Jamaica', 'JM', 'JAM');
INSERT INTO `countries` VALUES ('107', null, 'Japan', 'JP', 'JPN');
INSERT INTO `countries` VALUES ('108', null, 'Jordan', 'JO', 'JOR');
INSERT INTO `countries` VALUES ('109', null, 'Kazakhstan', 'KZ', 'KAZ');
INSERT INTO `countries` VALUES ('110', null, 'Kenya', 'KE', 'KEN');
INSERT INTO `countries` VALUES ('111', null, 'Kiribati', 'KI', 'KIR');
INSERT INTO `countries` VALUES ('113', null, 'Korea, Republic of', 'KR', 'KOR');
INSERT INTO `countries` VALUES ('114', null, 'Kuwait', 'KW', 'KWT');
INSERT INTO `countries` VALUES ('115', null, 'Kyrgyzstan', 'KG', 'KGZ');
INSERT INTO `countries` VALUES ('117', null, 'Latvia', 'LV', 'LVA');
INSERT INTO `countries` VALUES ('118', null, 'Lebanon', 'LB', 'LBN');
INSERT INTO `countries` VALUES ('119', null, 'Lesotho', 'LS', 'LSO');
INSERT INTO `countries` VALUES ('120', null, 'Liberia', 'LR', 'LBR');
INSERT INTO `countries` VALUES ('121', null, 'Libyan Arab Jamahiriya', 'LY', 'LBY');
INSERT INTO `countries` VALUES ('122', null, 'Liechtenstein', 'LI', 'LIE');
INSERT INTO `countries` VALUES ('123', null, 'Lithuania', 'LT', 'LTU');
INSERT INTO `countries` VALUES ('124', '1', 'Luxembourg', 'LU', 'LUX');
INSERT INTO `countries` VALUES ('125', null, 'Macao', 'MO', 'MAC');
INSERT INTO `countries` VALUES ('126', null, 'Macedonia, the Former Yugoslav Republic of', 'MK', 'MKD');
INSERT INTO `countries` VALUES ('127', null, 'Madagascar', 'MG', 'MDG');
INSERT INTO `countries` VALUES ('128', null, 'Malawi', 'MW', 'MWI');
INSERT INTO `countries` VALUES ('129', null, 'Malaysia', 'MY', 'MYS');
INSERT INTO `countries` VALUES ('130', null, 'Maldives', 'MV', 'MDV');
INSERT INTO `countries` VALUES ('131', null, 'Mali', 'ML', 'MLI');
INSERT INTO `countries` VALUES ('132', null, 'Malta', 'MT', 'MLT');
INSERT INTO `countries` VALUES ('133', null, 'Marshall Islands', 'MH', 'MHL');
INSERT INTO `countries` VALUES ('134', null, 'Martinique', 'MQ', 'MTQ');
INSERT INTO `countries` VALUES ('135', null, 'Mauritania', 'MR', 'MRT');
INSERT INTO `countries` VALUES ('136', null, 'Mauritius', 'MU', 'MUS');
INSERT INTO `countries` VALUES ('137', null, 'Mayotte', 'YT', 'NUL');
INSERT INTO `countries` VALUES ('138', null, 'Mexico', 'MX', 'MEX');
INSERT INTO `countries` VALUES ('139', null, 'Micronesia, Federated States of', 'FM', 'FSM');
INSERT INTO `countries` VALUES ('140', null, 'Moldova, Republic of', 'MD', 'MDA');
INSERT INTO `countries` VALUES ('141', null, 'Monaco', 'MC', 'MCO');
INSERT INTO `countries` VALUES ('142', null, 'Mongolia', 'MN', 'MNG');
INSERT INTO `countries` VALUES ('143', null, 'Montserrat', 'MS', 'MSR');
INSERT INTO `countries` VALUES ('144', null, 'Morocco', 'MA', 'MAR');
INSERT INTO `countries` VALUES ('145', null, 'Mozambique', 'MZ', 'MOZ');
INSERT INTO `countries` VALUES ('146', null, 'Myanmar', 'MM', 'MMR');
INSERT INTO `countries` VALUES ('147', null, 'Namibia', 'NA', 'NAM');
INSERT INTO `countries` VALUES ('148', null, 'Nauru', 'NR', 'NRU');
INSERT INTO `countries` VALUES ('149', null, 'Nepal', 'NP', 'NPL');
INSERT INTO `countries` VALUES ('150', '1', 'Netherlands', 'NL', 'NLD');
INSERT INTO `countries` VALUES ('151', null, 'Netherlands Antilles', 'AN', 'ANT');
INSERT INTO `countries` VALUES ('152', null, 'New Caledonia', 'NC', 'NCL');
INSERT INTO `countries` VALUES ('153', null, 'New Zealand', 'NZ', 'NZL');
INSERT INTO `countries` VALUES ('154', null, 'Nicaragua', 'NI', 'NIC');
INSERT INTO `countries` VALUES ('155', null, 'Niger', 'NE', 'NER');
INSERT INTO `countries` VALUES ('156', null, 'Nigeria', 'NG', 'NGA');
INSERT INTO `countries` VALUES ('157', null, 'Niue', 'NU', 'NIU');
INSERT INTO `countries` VALUES ('158', null, 'Norfolk Island', 'NF', 'NFK');
INSERT INTO `countries` VALUES ('159', null, 'Northern Mariana Islands', 'MP', 'MNP');
INSERT INTO `countries` VALUES ('160', null, 'Norway', 'NO', 'NOR');
INSERT INTO `countries` VALUES ('161', null, 'Oman', 'OM', 'OMN');
INSERT INTO `countries` VALUES ('162', null, 'Pakistan', 'PK', 'PAK');
INSERT INTO `countries` VALUES ('163', null, 'Palau', 'PW', 'PLW');
INSERT INTO `countries` VALUES ('164', null, 'Palestinian Territory, Occupied', 'PS', 'NUL');
INSERT INTO `countries` VALUES ('165', null, 'Panama', 'PA', 'PAN');
INSERT INTO `countries` VALUES ('166', null, 'Papua New Guinea', 'PG', 'PNG');
INSERT INTO `countries` VALUES ('167', null, 'Paraguay', 'PY', 'PRY');
INSERT INTO `countries` VALUES ('168', null, 'Peru', 'PE', 'PER');
INSERT INTO `countries` VALUES ('169', null, 'Philippines', 'PH', 'PHL');
INSERT INTO `countries` VALUES ('170', null, 'Pitcairn', 'PN', 'PCN');
INSERT INTO `countries` VALUES ('171', null, 'Poland', 'PL', 'POL');
INSERT INTO `countries` VALUES ('172', '1', 'Portugal', 'PT', 'PRT');
INSERT INTO `countries` VALUES ('173', null, 'Puerto Rico', 'PR', 'PRI');
INSERT INTO `countries` VALUES ('174', null, 'Qatar', 'QA', 'QAT');
INSERT INTO `countries` VALUES ('175', null, 'Reunion', 'RE', 'REU');
INSERT INTO `countries` VALUES ('176', null, 'Romania', 'RO', 'ROM');
INSERT INTO `countries` VALUES ('177', null, 'Russian Federation', 'RU', 'RUS');
INSERT INTO `countries` VALUES ('178', null, 'Rwanda', 'RW', 'RWA');
INSERT INTO `countries` VALUES ('179', null, 'Saint Helena', 'SH', 'SHN');
INSERT INTO `countries` VALUES ('180', null, 'Saint Kitts and Nevis', 'KN', 'KNA');
INSERT INTO `countries` VALUES ('181', null, 'Saint Lucia', 'LC', 'LCA');
INSERT INTO `countries` VALUES ('182', null, 'Saint Pierre and Miquelon', 'PM', 'SPM');
INSERT INTO `countries` VALUES ('183', null, 'Saint Vincent and the Grenadines', 'VC', 'VCT');
INSERT INTO `countries` VALUES ('184', null, 'Samoa', 'WS', 'WSM');
INSERT INTO `countries` VALUES ('185', null, 'San Marino', 'SM', 'SMR');
INSERT INTO `countries` VALUES ('186', null, 'Sao Tome and Principe', 'ST', 'STP');
INSERT INTO `countries` VALUES ('187', null, 'Saudi Arabia', 'SA', 'SAU');
INSERT INTO `countries` VALUES ('188', null, 'Senegal', 'SN', 'SEN');
INSERT INTO `countries` VALUES ('189', null, 'Serbia and Montenegro', 'CS', 'NUL');
INSERT INTO `countries` VALUES ('190', null, 'Seychelles', 'SC', 'SYC');
INSERT INTO `countries` VALUES ('191', null, 'Sierra Leone', 'SL', 'SLE');
INSERT INTO `countries` VALUES ('192', null, 'Singapore', 'SG', 'SGP');
INSERT INTO `countries` VALUES ('193', null, 'Slovakia', 'SK', 'SVK');
INSERT INTO `countries` VALUES ('194', null, 'Slovenia', 'SI', 'SVN');
INSERT INTO `countries` VALUES ('195', null, 'Solomon Islands', 'SB', 'SLB');
INSERT INTO `countries` VALUES ('196', null, 'Somalia', 'SO', 'SOM');
INSERT INTO `countries` VALUES ('197', null, 'South Africa', 'ZA', 'ZAF');
INSERT INTO `countries` VALUES ('198', null, 'South Georgia and the South Sandwich Islands', 'GS', 'NUL');
INSERT INTO `countries` VALUES ('199', '1', 'Spain', 'ES', 'ESP');
INSERT INTO `countries` VALUES ('200', null, 'Sri Lanka', 'LK', 'LKA');
INSERT INTO `countries` VALUES ('201', null, 'Sudan', 'SD', 'SDN');
INSERT INTO `countries` VALUES ('202', null, 'Suriname', 'SR', 'SUR');
INSERT INTO `countries` VALUES ('203', null, 'Svalbard and Jan Mayen', 'SJ', 'SJM');
INSERT INTO `countries` VALUES ('204', null, 'Swaziland', 'SZ', 'SWZ');
INSERT INTO `countries` VALUES ('205', null, 'Sweden', 'SE', 'SWE');
INSERT INTO `countries` VALUES ('206', null, 'Switzerland', 'CH', 'CHE');
INSERT INTO `countries` VALUES ('207', null, 'Syrian Arab Republic', 'SY', 'SYR');
INSERT INTO `countries` VALUES ('208', null, 'Taiwan, Province of China', 'TW', 'TWN');
INSERT INTO `countries` VALUES ('209', null, 'Tajikistan', 'TJ', 'TJK');
INSERT INTO `countries` VALUES ('210', null, 'Tanzania, United Republic of', 'TZ', 'TZA');
INSERT INTO `countries` VALUES ('211', null, 'Thailand', 'TH', 'THA');
INSERT INTO `countries` VALUES ('212', null, 'Timor-Leste', 'TL', 'NUL');
INSERT INTO `countries` VALUES ('213', null, 'Togo', 'TG', 'TGO');
INSERT INTO `countries` VALUES ('214', null, 'Tokelau', 'TK', 'TKL');
INSERT INTO `countries` VALUES ('215', null, 'Tonga', 'TO', 'TON');
INSERT INTO `countries` VALUES ('216', null, 'Trinidad and Tobago', 'TT', 'TTO');
INSERT INTO `countries` VALUES ('217', null, 'Tunisia', 'TN', 'TUN');
INSERT INTO `countries` VALUES ('218', null, 'Turkey', 'TR', 'TUR');
INSERT INTO `countries` VALUES ('219', null, 'Turkmenistan', 'TM', 'TKM');
INSERT INTO `countries` VALUES ('220', null, 'Turks and Caicos Islands', 'TC', 'TCA');
INSERT INTO `countries` VALUES ('221', null, 'Tuvalu', 'TV', 'TUV');
INSERT INTO `countries` VALUES ('222', null, 'Uganda', 'UG', 'UGA');
INSERT INTO `countries` VALUES ('223', null, 'Ukraine', 'UA', 'UKR');
INSERT INTO `countries` VALUES ('224', null, 'United Arab Emirates', 'AE', 'ARE');
INSERT INTO `countries` VALUES ('225', null, 'United Kingdom', 'GB', 'GBR');
INSERT INTO `countries` VALUES ('226', null, 'United States', 'US', 'USA');
INSERT INTO `countries` VALUES ('227', null, 'United States Minor Outlying Islands', 'UM', '\r');
INSERT INTO `countries` VALUES ('228', null, 'Uruguay', 'UY', 'URY');
INSERT INTO `countries` VALUES ('229', null, 'Uzbekistan', 'UZ', 'UZB');
INSERT INTO `countries` VALUES ('230', null, 'Vanuatu', 'VU', 'VUT');
INSERT INTO `countries` VALUES ('231', null, 'Venezuela', 'VE', 'VEN');
INSERT INTO `countries` VALUES ('232', null, 'Viet Nam', 'VN', 'VNM');
INSERT INTO `countries` VALUES ('233', null, 'Virgin Islands, British', 'VG', 'VGB');
INSERT INTO `countries` VALUES ('234', null, 'Virgin Islands, U.s.', 'VI', 'VIR');
INSERT INTO `countries` VALUES ('235', null, 'Wallis and Futuna', 'WF', 'WLF');
INSERT INTO `countries` VALUES ('236', null, 'Western Sahara', 'EH', 'ESH');
INSERT INTO `countries` VALUES ('237', null, 'Yemen', 'YE', 'YEM');
INSERT INTO `countries` VALUES ('238', null, 'Zambia', 'ZM', 'ZMB');
INSERT INTO `countries` VALUES ('239', null, 'Zimbabwe', 'ZW', 'ZWE');
