<style>
    
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #efefef;
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
    }
    
    div#more-information
    {
        height: 100%;
    }

</style>
<center>
    <div id="welcome">
        <center>
        <br />
        <span id="zf-name">
		<h1>Welcome to the Zend Framework!<h1 />
        <h3>Up and Running With WAMP ! <h3 />
		</span>
        <div id="more-information">
            <br />
			<span>Your Site name is :</span><br/>
            <?=$this->address;?>
        </div>
    </div>
</center>