<style>
    
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
    }
    
    div#more-information
    {
        height: 100%;
        color: blue;
    }

</style>

<center>
    <div id="welcome">
        <center>
        <h1><span id="zf-name">Welcome to the Zend Framework!</span><h1/>
        
        <div id="more-information">
         
          <p>index Action </p>
        </div>
    </div>
</center>