<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?= $this->headTitle(); ?>
        <?= $this->headMeta()->appendHttpEquiv('Content-Language', 'en-US')
                             ->appendHttpEquiv('Content-Type','text/html;charset=utf-8'); ?>
        <?= $this->headStyle(); ?>
    </head>
