<?php echo $this->doctype(); ?>
<html>
    <head>

        <?php
            $this->headLink()
                ->prependStylesheet('/css/global.css');
        ?>
        <?php echo $this->headLink(); ?>
    </head>
    <body>
        <div class="header">
            <h1>My Website</h1>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Products</a></li>
                <li><a href="#">Contact Us</a></li>
            </ul>
        </div>
        <div class="content">
            <?php echo $this->layout()->content; ?>
        </div>
        <div class="footer">
            
        </div>
    </body>
</html>