<?php

/**
 * Model_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6698 2009-11-10 17:58:02Z jwage $
 */
class Model_User extends Model_Base_User
{
    const NOT_FOUND = 1;
    const WRONG_PW  = 2;

    /**
     * Perform authentication of a user
     * @param string $username
     * @param string $password
     */
    public static function authenticate($username, $password)
    {
        $user = Doctrine_Core::getTable('Model_User')->findOneByUsername($username);
        if ($user)
        {
            if ($user->password == $password)
                return $user;

            throw new Exception(self::WRONG_PW);
        }
        throw new Exception(self::NOT_FOUND);
    }
}